// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARWdbvA9JSiqaTFyJYg4Ke_qMyxmnU4Ig',
    appId: '1:103972445421:web:9efbaef2b63a7ee2ad80e4',
    messagingSenderId: '103972445421',
    projectId: 'test1-93f65',
    authDomain: 'test1-93f65.firebaseapp.com',
    storageBucket: 'test1-93f65.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARoVA1bYAwe1Qei-iZnengsMrorffHCOU',
    appId: '1:103972445421:android:75920af4ec5c3474ad80e4',
    messagingSenderId: '103972445421',
    projectId: 'test1-93f65',
    storageBucket: 'test1-93f65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOjrwUGrTvBD_SLJG51Qhs-qz5rB7TxoQ',
    appId: '1:103972445421:ios:be8f6b3ad757d8e3ad80e4',
    messagingSenderId: '103972445421',
    projectId: 'test1-93f65',
    storageBucket: 'test1-93f65.appspot.com',
    iosClientId: '103972445421-drl5fu4nujb0tubusu8ho5q20vru9vlt.apps.googleusercontent.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOjrwUGrTvBD_SLJG51Qhs-qz5rB7TxoQ',
    appId: '1:103972445421:ios:be8f6b3ad757d8e3ad80e4',
    messagingSenderId: '103972445421',
    projectId: 'test1-93f65',
    storageBucket: 'test1-93f65.appspot.com',
    iosClientId: '103972445421-drl5fu4nujb0tubusu8ho5q20vru9vlt.apps.googleusercontent.com',
    iosBundleId: 'com.example.test1',
  );
}
